name = "LinearProgramming"
uuid = "eadb3a9a-47bd-4d5d-9c87-f226d6d2e08d"
authors = ["Alessandro Ciffo <diogene.ciffo@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
